knp_paginator:
    page_range: 5
    default_options:
        page_name: p
        sort_field_name: s
        sort_direction_name: d
        distinct: true
    template:
        pagination: 'pagination/sliding_with_last.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
