# See docs at: http://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure image cache directory
    cache: default

    # configure resolvers
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    # configure filter sets
    filter_sets:
        # Filter for resizing images to max 800x800
        recorte:
            quality: 80
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [800, 800]
                    mode: inset

        # Filter for creating thumbnails 200x200
        thumbnail:
            quality: 80
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: inset
