twig:
    file_name_pattern: '*.twig'
    globals:
        google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
        google_maps_map_id: '%env(GOOGLE_MAPS_MAP_ID)%'

when@test:
    twig:
        strict_variables: true
